# Generated by Django 4.0.3 on 2022-04-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='movie')),
                ('category', models.CharField(choices=[('A', 'ACTION'), ('D', 'DRAMA'), ('C', 'COMEDY'), ('R', 'ROMANCE')], max_length=1)),
                ('language', models.CharField(choices=[('E', 'ENGLISH'), ('D', 'Deutsch')], max_length=2)),
                ('status', models.CharField(choices=[('RA', 'RECENTLY WATCH'), ('MW', 'MOST WATCHED'), ('TR', 'TOP RATED')], max_length=2)),
                ('year_of_production', models.DateField()),
                ('view_count', models.ImageField(default=0, upload_to='')),
            ],
        ),
    ]
