# Generated by Django 4.0.3 on 2022-04-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Action', 'ACTION'), ('Drama', 'DRAMA'), ('Comedy', 'COMEDY'), ('Romance', 'ROMANCE')], max_length=10),
        ),
    ]
