# Generated by Django 4.0.3 on 2022-04-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_language_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('deutsch', 'Deutsch')], max_length=10),
        ),
    ]
