# Generated by Django 5.0 on 2023-12-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_movie_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('deutsch', 'Deutsch'), ('hindi', 'HINDI')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Watch_link',
        ),
    ]
